// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bixofsktenchkaiguhlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpeG9mc2t0ZW5jaGthaWd1aGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTAyMjUsImV4cCI6MjA2NjY2NjIyNX0.ZRUfLBp4eG6BiWbQ_sQeDmJZvU24QOE7lVNR2qAkPAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);